// Copyright 2022
// Autogenerated from Pigeon (v12.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package nd.flutter.plugins.gpu_video_filters

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FilterApi {
  fun create(vertexShader: String, fragmentShader: String, defaults: Map<String, Double>, arrays: Map<String, DoubleArray>, texture: String?): Long
  fun exportVideoFile(filterId: Long, asset: Boolean, input: String, output: String, format: String, period: Long): Long
  fun setFloatParameter(filterId: Long, key: String, value: Double)
  fun setFloatArrayParameter(filterId: Long, key: String, value: DoubleArray)
  fun setBitmapParameter(filterId: Long, key: String, data: ByteArray)
  fun setBitmapSourceParameter(filterId: Long, key: String, asset: Boolean, path: String)
  fun dispose(filterId: Long)

  companion object {
    /** The codec used by FilterApi. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
    /** Sets up an instance of `FilterApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: FilterApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.FilterApi.create", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val vertexShaderArg = args[0] as String
            val fragmentShaderArg = args[1] as String
            val defaultsArg = args[2] as Map<String, Double>
            val arraysArg = args[3] as Map<String, DoubleArray>
            val textureArg = args[4] as String?
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.create(vertexShaderArg, fragmentShaderArg, defaultsArg, arraysArg, textureArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.FilterApi.exportVideoFile", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val assetArg = args[1] as Boolean
            val inputArg = args[2] as String
            val outputArg = args[3] as String
            val formatArg = args[4] as String
            val periodArg = args[5].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.exportVideoFile(filterIdArg, assetArg, inputArg, outputArg, formatArg, periodArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.FilterApi.setFloatParameter", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val keyArg = args[1] as String
            val valueArg = args[2] as Double
            var wrapped: List<Any?>
            try {
              api.setFloatParameter(filterIdArg, keyArg, valueArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.FilterApi.setFloatArrayParameter", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val keyArg = args[1] as String
            val valueArg = args[2] as DoubleArray
            var wrapped: List<Any?>
            try {
              api.setFloatArrayParameter(filterIdArg, keyArg, valueArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.FilterApi.setBitmapParameter", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val keyArg = args[1] as String
            val dataArg = args[2] as ByteArray
            var wrapped: List<Any?>
            try {
              api.setBitmapParameter(filterIdArg, keyArg, dataArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.FilterApi.setBitmapSourceParameter", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val keyArg = args[1] as String
            val assetArg = args[2] as Boolean
            val pathArg = args[3] as String
            var wrapped: List<Any?>
            try {
              api.setBitmapSourceParameter(filterIdArg, keyArg, assetArg, pathArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.FilterApi.dispose", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            var wrapped: List<Any?>
            try {
              api.dispose(filterIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VideoPreviewApi {
  fun create(): Long
  fun connect(textureId: Long, filterId: Long, embedded: Boolean)
  fun disconnect(textureId: Long, embedded: Boolean)
  fun setSource(textureId: Long, path: String, asset: Boolean, embedded: Boolean)
  fun resume(textureId: Long, embedded: Boolean)
  fun pause(textureId: Long, embedded: Boolean)
  fun dispose(textureId: Long, embedded: Boolean)

  companion object {
    /** The codec used by VideoPreviewApi. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
    /** Sets up an instance of `VideoPreviewApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: VideoPreviewApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.VideoPreviewApi.create", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.create())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.VideoPreviewApi.connect", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val filterIdArg = args[1].let { if (it is Int) it.toLong() else it as Long }
            val embeddedArg = args[2] as Boolean
            var wrapped: List<Any?>
            try {
              api.connect(textureIdArg, filterIdArg, embeddedArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.VideoPreviewApi.disconnect", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val embeddedArg = args[1] as Boolean
            var wrapped: List<Any?>
            try {
              api.disconnect(textureIdArg, embeddedArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.VideoPreviewApi.setSource", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val pathArg = args[1] as String
            val assetArg = args[2] as Boolean
            val embeddedArg = args[3] as Boolean
            var wrapped: List<Any?>
            try {
              api.setSource(textureIdArg, pathArg, assetArg, embeddedArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.VideoPreviewApi.resume", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val embeddedArg = args[1] as Boolean
            var wrapped: List<Any?>
            try {
              api.resume(textureIdArg, embeddedArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.VideoPreviewApi.pause", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val embeddedArg = args[1] as Boolean
            var wrapped: List<Any?>
            try {
              api.pause(textureIdArg, embeddedArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_gpu_video_filters.VideoPreviewApi.dispose", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0].let { if (it is Int) it.toLong() else it as Long }
            val embeddedArg = args[1] as Boolean
            var wrapped: List<Any?>
            try {
              api.dispose(textureIdArg, embeddedArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
